name: dotnet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      release:
        required: true
        default: "false"
      majorVersion:
        required: true
        default: "0"
      minorVersion:
        required: true
        default: "1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          6.0.x
          7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  publish:
    needs: build
    if: (github.ref == 'refs/heads/main' && github.event.inputs.release == 'true')
    runs-on: macos-latest
    env:
      releaseVersion: ${{ github.event.inputs.majorVersion }}.${{ github.event.inputs.minorVersion }}.${{ github.run_number }}
    steps:
      - name: Version
        run: echo Releasing version $releaseVersion
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      # publish
      - name: Publish
        run: dotnet publish -p:Configuration=Release -p:DebugType=None -p:DebugSymbols=false -p:Version=${{env.releaseVersion}}
      - name: Zip
        run: (cd HeliumCat/bin/Release/net6.0/publish ; rm HeliumCat ; zip -r HeliumCat_v${{env.releaseVersion}}.zip *)
      # create a release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{env.releaseVersion}}
          files: |
            HeliumCat/bin/Release/net6.0/publish/HeliumCat_v${{env.releaseVersion}}.zip
